package com.projectRaj.eCommerceAPI.models;

public enum Category {
    ELECTRONICS,
    CLOTHING,
    BOOKS,
    HOME_APPLIANCES,
    SPORTS_EQUIPMENT,
    TOYS,
    JEWELRY,
    BEAUTY,
    FOOD,
    FURNITURE,
    AUTOMOTIVE,
    PET_SUPPLIES,
    HEALTH_AND_WELLNESS,
    MUSIC,
    MOVIES,
    GAMES,
    ART_AND_CRAFTS,
    GARDEN_AND_OUTDOOR,
    COMPUTERS,
    SHOES,
    BAGS,
    ACCESSORIES,
    FITNESS,
    HOME_DECOR,
    TRAVEL,
    OFFICE_SUPPLIES,
    BABY_AND_CHILD,
    PARTY_SUPPLIES,
    HOBBIES,
    CAMERAS_AND_PHOTOGRAPHY,
    INDUSTRIAL_AND_SCIENTIFIC,
    COLLECTIBLES,
    OTHER
}


